version: "3.8"

services:
    flask:
        build: .
        container_name: flask_app
        image: flask_app
        ports:
            - 5000:5000
            - 5678:5678
        restart: always
        environment:
            ADMINS: ${ADMINS}
            FLASK_APP: ${FLASK_APP}
            FLASK_ENV: ${FLASK_ENV}
            MAIL_SERVER: ${MAIL_SERVER}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USE_TLS: ${MAIL_USE_TLS}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MS_TRANSLATOR_KEY: ${MS_TRANSLATOR_KEY}
        volumes:
            - .:/app
        networks:
            redis_flask_app:
        command: ["sh", "-c",
                  "pip install debugpy -t /tmp && \
                  python /tmp/debugpy \
                  --wait-for-client --listen 0.0.0.0:5678 \
                  -m flask run --host 0.0.0.0 --port 5000"]

networks:
    redis_flask_app:
        driver: bridge
