version: "3.8"

services:
    elastic:
        container_name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        environment:
          ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
          discovery.type: single-node
        ports:
          - 9200:9200
          - 9300:9300
        networks:
          - flask_blog

    flask:
        build: .
        container_name: flask_app
        image: flask_app
        ports:
            - 5000:5000
            - 5678:5678
        restart: always
        environment:
            ADMINS: ${ADMINS}
            FLASK_APP: ${FLASK_APP}
            FLASK_ENV: ${FLASK_ENV}
            MAIL_SERVER: ${MAIL_SERVER}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USE_TLS: ${MAIL_USE_TLS}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MS_TRANSLATOR_KEY: ${MS_TRANSLATOR_KEY}
        volumes:
            - .:/app
        networks:
            - flask_blog
        command: ["sh", "-c",
                  "pip install debugpy -t /tmp && \
                  python /tmp/debugpy \
                  --wait-for-client --listen 0.0.0.0:5678 \
                  -m flask run --host 0.0.0.0 --port 5000"]

networks:
    flask_blog:
        driver: bridge
