version: "3.8"

services:
    flask:
        build: .
        container_name: flask_app
        image: flask_app
        ports:
            - 5000:5000
            - 5678:5678
        restart: always
        environment:
            FLASK_APP: app.py
            FLASK_ENV: development
            # FLASK_ENV: production
        volumes:
            - .:/app
        networks:
            redis_flask_app:
        command: [
            "sh", "-c",
            "pip install debugpy -t /tmp && \
            python /tmp/debugpy \
                --wait-for-client --listen 0.0.0.0:5678 \
                -m flask run --host 0.0.0.0 --port 5000"
        ]

    redis:
        image: redis
        container_name: redis_cache
        networks:
            redis_flask_app:
                aliases:
                    - redis


networks:
    redis_flask_app:
        driver: bridge
