version: "3.8"

services:
    elastic:
        container_name: elastic
        build:
            context: .
            dockerfile: elastic.Dockerfile
        image: elastic
        networks:
            flask_blog:
                aliases:
                    - elastic

    postgres:
        container_name: postgres
        image: postgres:12-alpine
        volumes:
            - postgres-db:/var/lib/postgresql/data
        networks:
            flask_blog:
                aliases:
                    - postgres

    flask:
        build: .
        container_name: flask_app
        image: flask_app
        ports:
            - 5000:5000
            - 5678:5678 # here for debugging
        restart: always
        env_file: .env
        volumes:
            - .:/app
        networks:
            flask_blog:
        command: ./boot.sh

    # redis:
    #     image: redis
    #     container_name: redis_cache
    #     networks:
    #         flask_blog:
    #             aliases:
    #                 - redis
    #     volumes:
    #         - redis-cache:/var/lib/redis/data

volumes:
    postgres-db:
    # redis-cache:

networks:
    flask_blog:
        driver: bridge
