version: "3.8"

services:
    elastic:
        container_name: elastic
        build:
            context: .
            dockerfile: elastic.Dockerfile
        image: elastic
        networks:
            flask_blog:
                aliases:
                    - elastic

    postgres:
        container_name: postgres
        image: postgres:12-alpine
        volumes:
            - postgres-db:/var/lib/postgresql/data
        networks:
            flask_blog:
                aliases:
                    - postgres

    flask:
        build: .
        image: flask_app
        container_name: flask_app
        ports:
            - 5000:5000
            - 5678:5678 # here for debugging
        restart: always
        env_file: .env
        volumes:
            - .:/app
        networks:
            flask_blog:
        command: ./boot.sh

    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        networks:
            flask_blog:
                aliases:
                    - redis
        volumes:
            - redis-cache:/var/lib/redis/data

    rq_worker:
        build: .
        image: flask_app
        container_name: rq_worker
        env_file: .env
        depends_on:
            - redis
        networks:
            flask_blog:
                aliases:
                    - rq_worker
        entrypoint: rq
        command: worker -u ${REDIS_URL} flask_blog-tasks

volumes:
    postgres-db:
    redis-cache:

networks:
    flask_blog:
        driver: bridge
